### ISSUE TITLE
8bitdo iCade Controller Crashes Provenance

### ISSUE THREAD

**Issue by jpete24** [jasarien/Provenance#115]
Just noticed that the latest build crashes the entire app once I press any button on the 8bitdo NES30 Controller which I have in iCade mode. Not sure what is causing it.

**Comment by jasarien** [comment]
If you could try and dig out a crash log from your device, that might be useful. It'll be tricky for me to track this down, since I don't have any iCade devices to test with, so I won't be able to reproduce it.

**Comment by jpete24** [comment]
Where do I find it?

**Comment by jasarien** [comment]
In the Devices window in Xcode, select your device and click the "view device logs" button. Wait for it to process any new crash logs and then order by date. The latest log should be the crash you're talking about.

**Comment by jpete24** [comment]
How do you want it?

**Comment by jasarien** [comment]
You should be able to attach the file to a comment here.

**Comment by jpete24** [comment]
Github's uploader is being silly. Grab it here.

https://dl.dropboxusercontent.com/u/466526/Provenance%20%209-27-15%2C%201-07%20PM.crash

**Comment by jasarien** [comment]
Just pushed a possible fix. Try it out and let me know.

**Comment by jpete24** [comment]
Doesn't crash anymore, but the controller configuration is garbage now. D pad doesn't work, and the bumper buttons seem to be opposite?

**Comment by jasarien** [comment]
Pushed moar codez. Give it a whirl.

**Comment by jpete24** [comment]
You broke it. Still doesn't work, but at least it doesn't crash? See video.

https://www.dropbox.com/s/m5cxcqsswt37cdw/video%20sep%2027%2C%202%2007%2054%20pm.mov?dl=0

**Comment by jpete24** [comment]
It seems like the buttons are inverted from what they use to be as well. Not sure if that gives you any signs of what is going on.

**Comment by jasarien** [comment]
One more push. Pull the latest and try again please?

**Comment by jpete24** [comment]
Still not working, and its crashing again. I'll try to send the crash file again later.

**Comment by jpete24** [comment]
Did you write the 8bitdo icade portion? I thought somebody did a fork of that?

**Comment by jasarien** [comment]
I didn't write it. @josejulio wrote it.

**Comment by jasarien** [comment]
As soon as you can get the crash log to me, I'll take another look at it. Does it crash when you press a particular button?

**Comment by jpete24** [comment]
It crashes when any button is pressed this time. Last time it only crashed when you hit the d pad.

**Comment by jasarien** [comment]
Ok, well the sooner I see the crash log the sooner I can take a look.

**Comment by indirect** [comment]
Here's a crash log from an SNES30 connected to an iPad Air. http://files.arko.net/0a0O1C2u0X2L/Provenance%20%209-27-15,%205-47%20PM.crash

**Comment by jpete24** [comment]
Here is my last crash log! Thanks for looking into this...sounds like I'm not the only one experiencing the issue. I wonder where in the updates that it stopped working. I know the last build I was using that worked with this properly was on August 31, 2015.

https://dl.dropboxusercontent.com/u/466526/Provenance%20%209-27-15%2C%202-38%20PM.crash

**Comment by jasarien** [comment]
I pushed another fix. Pull the latest and Give it another try please.

This is the problem with developing for hardware I don't have access to :P

**Comment by jpete24** [comment]
I should just buy you one to be sure we have continuous support. That would kind of be like donations, right? :) I'll give it a shot after work today.

**Comment by josejulio** [comment]
Sorry, i haven't had much time lately, if there is still problems, i'll try to give a look today.

**Comment by jasarien** [comment]
No worries. I'm fairly confident that the latest push will solve it. I just have no controller to test it with. If not, I'll let you take a look and see if you know what's up.

**Comment by indirect** [comment]
Thanks! (I'm also happy to chip in to send an NES30 or SNES30 to @jasarien :P)

**Comment by jasarien** [comment]
Has anyone tried he latest code with an iCade controller yet? :P are the issues solved?

**Comment by jpete24** [comment]
I already asked him to DM me on Twitter. I'd totally split it with you. ;)

I'll be testing it tonight. Give me a couple hours.

Josh

**Comment by jpete24** [comment]
Ok, it works....with some exceptions. The D-pad works now without crashing (so does the J-stick) but the button configuration is all messed up:

A is now B
Y is now A
L is now R
R is now L
X is now Select

Select and Start seem to work correctly though!

**Comment by jpete24** [comment]
Scratch that...just tested it with an old build. the only buttons that seem to be switched are:

Y and A 
 L and R

You swap those, and were back in business.

**Comment by indirect** [comment]
I can confirm that Y and A are swapped; didn't have a game handy to check L and R, but it sounds plausible. Turns out the biggest problem I was having was external keyboards configured to use Dvorak in settings. :sweat_smile:

**Comment by jasarien** [comment]
I've reverted the controls to their original mapping. Should be fixed now.

**Comment by jpete24** [comment]
Sorry to give the bad news.... but its still not working right. So it seems like the A & B buttons are flipped now, and once you press the button it acts like the emulator doesn't want to depress the button (constantly being pressed). L & R buttons seem configured right though. See video:

https://www.dropbox.com/s/6ef0xshzcd8oky8/Video%20Sep%2029%2C%209%2018%2037%20PM.mov?dl=0

**Comment by jasarien** [comment]
Well I reverted the mapping a to what they were originally. So if they're flipped now they were flipped before too. I'll take another look tonight.

**Comment by jasarien** [comment]
Just pushed a fix that should solve the button remaining pressed after releasing. But as I said I reverted the mapping so it's as it was when originally implemented. If the buttons are flipped now then they were before as well.

**Comment by jasarien** [comment]
If someone could test this out and let me know, so I can finally close this issue
![image](https://cloud.githubusercontent.com/assets/104444/10208196/7be1975c-67c9-11e5-8367-ad94f4db016d.jpg)

**Comment by jpete24** [comment]
I'm on it tonight.

Josh

**Comment by jpete24** [comment]
ER MY GAWD.....You did it.

However I feel that A & B are still flipped around for the 8bitdo controllers. I would really like you to fix that if you could, as it wasn't what it was originally from the build on August 29th. Your thoughts?

**Comment by josejulio** [comment]
What firmware are you using (of your 8bitdo controller)?

**Comment by josejulio** [comment]
Also, on iOS8, there was a severe lag at the starting of the rom (caused by
iOS bluetooth keyboard), I'm curious if is still present. Thanks!

On Wed, Sep 30, 2015 at 6:20 PM, Josejulio Martínez <finwemartinez@gmail.com
> wrote:

> What firmware are you using (of your 8bitdo controller)?
>

**Comment by jpete24** [comment]
I'm on the latest firmware for my 8bitdo nes30 pro. Thoughts?

Josh

**Comment by josejulio** [comment]
I'll pull the code and test on my phone, i also have a nes30 pro and i'm
not sure if i have the latest firmware, but will check though.

**Comment by jpete24** [comment]
Make it happen my friend.

Josh

**Comment by josejulio** [comment]
Ok, tested.  I can confirm (used Mario rpg and mario&luigi superstar saga) that a&b and x&y are switched. Also noticed several other things that aren't working as they should. I'll try to fix them this week (possibly tackle some issues tomorrow).




The list of issues that found so far(icade controllers) are:

Can't "unbind" the controller from the menu.

The controller won't work if you load a save.

Switched buttons.

Not able to assign icade controller to a player(this would be a feature).




Can you confirm that you also have these issues? Thanks!










—

**Comment by jpete24** [comment]
Not sure about the unbind and the load state issue. I've loaded states and it works fine, I just having an issue with the buttons being flipped.

**Comment by jasarien** [comment]
I swapped A/B and Y/X. Give it a try.

**Comment by indirect** [comment]
I can confirm that buttons are now in the right place! As @josejulio noted, these problems still exist:

  - Controller stops working as soon as state is loaded
  - Can't "unbind" controller
  - Can't assign iCade controller to player

Tested on iPhone 6S Plus with SNES30.

**Comment by jasarien** [comment]
Cool. I'll let @josejulio look into those ones as he'll be able to test them with hardware.

**Comment by jpete24** [comment]
@josejulio any progress or thoughts?

**Comment by josejulio** [comment]
I guess that this https://github.com/josejulio/Provenance/commit/0af0231c07b21b9955d5ec6541a8c8baf399243f  switched again the x/y and a/b. I'm looking onto the controller stops working as soon as state is loaded.

**Comment by josejulio** [comment]
It seems that only pressing the menu button disables the icade control. I'm checking it out.

**Comment by jasarien** [comment]
> I guess that this 0af0231 switched again the x/y and a/b. I'm looking onto the controller stops working as soon as state is loaded.

Yeah, I keep forgetting to update the iCade controller when I change the system button mappings >.<

You've got the pad, can you set it straight? :D

**Comment by josejulio** [comment]
I got it, don't worry, I'll make a pull request today.



—

**Comment by jasarien** [comment]
Life saver.

**Comment by josejulio** [comment]
Seems that is an issue on iOS 9, when an UIActionSheet is presented, not sure why but the iCadeController stops workings. Just made a pull request with a fix. (Also swapped the A/B and X/Y)

**Comment by jasarien** [comment]
I've merged @josejulio's pull request, so I'll tentatively close this issue for now. If there are still issues surrounding iCade controls, please raise a new one, as this one has gone on for 54 comments XD.

**Comment by jpete24** [comment]
I can confirm we got this working again. Nice work team!

![i-love-it-when-a-plan-comes-together](https://cloud.githubusercontent.com/assets/14237434/10297831/92126880-6b9d-11e5-87e8-99fc8afcf0f9.jpg)
