### ISSUE TITLE
Menu button on Nimbus quits game

### ISSUE THREAD

**Issue by thefinerarts** [jasarien/Provenance#553]
Originally fixed with #503 the Menu button on my Nimbus controller now again brings me back straight to the Library instead of opening the in-game-menu. It still works with the Apple Remote, but only when the Nimbus is completely disconnected (1.3.2/672, tvOS 10.2).

**Comment by techdragon** [comment]
I'm seeing the same behaviour. I suspect it could be related to tvOS 10.2

**Comment by ryanjmclaughlin** [comment]
This began for me as well immediately after the 10.2 update.  I have some other apps with controller issues as well so maybe apple changed the controller APIs?

**Comment by mr100percent** [comment]
Also same issue occurring. Was not occurring on tvOS 10.1 and is also present when Nimbus controller is used.

**Comment by tomp8628** [comment]
I unpaired my controllers in the ATV settings, restarted and then repaired and seems to work again. May be a problem with 10.2 update carrying over controller settings.

**Comment by thefinerarts** [comment]
Doesn't work here unfortunately.

**Comment by piercifani** [comment]
Same thing here, pretty frustrating

**Comment by techdragon** [comment]
The double Siri button method works reliably enough for me to be able to use the menu again. It's not a fix, but it's definitely proving to be a decent workaround for the time being.

**Comment by JoeMatt** [comment]
A quick hack is to change

` [[UIApplication sharedApplication].keyWindow addGestureRecognizer:_menuGestureRecognizer];`
to
` [self.view addGestureRecognizer:_menuGestureRecognizer];`
in `PVEmulatorViewController.m`

It's a little glitchy, maybe it needs to be in the parent vc if someone wants to check that.

**Comment by carloperez** [comment]
Seeing the same after the update along with what feels like a more sluggish interface.

**Comment by theuriah** [comment]
Same here. Running v.1.3.6 on latest tvOS today. 10.2.1 i think.

**Comment by JoeMatt** [comment]
This has been fixed in #561

**Comment by lolkthxbai** [comment]
@JoeMatt has #561 been merged into master branch? I just pulled the master branch and it said it was already up to date but the issue still occurs. I'm guessing it hasn't...?

**Comment by JoeMatt** [comment]
@lolkthxbai no it's not and #561 has moved to #566

**Comment by shinkei13** [comment]
Possibly unrelated, but I'm getting a similar bug when using the menu button on my remote whenever I have an 8bitdo controller paired. Menu takes me straight out of Provenance, but double pressing Siri gets me the in-game menu.

Running ProvenanceTV 1.3.2(685), git revision f47caf3 on tvOS 11.

**Comment by appletv4** [comment]
I’m seeing the same problem but with the regular Siri remote , hitting menu during a game takes me out the app
When I go back in the app the menu pop up is there

**Comment by jasarien** [comment]
I have tested the latest version (after merging @JoeMatt’s pull request which contains the mentioned fixes for this issue), and I cannot reproduce the menu button quitting the game.

If this is still a problem for anyone, please move the discussion over to #522
