### ISSUE TITLE
Button mapping customisation for iOS 7 game controllers.

### ISSUE THREAD

**Issue by jasarien** [jasarien/Provenance#56]
Allow custom button mappings for physical controllers.

**Comment by appletv4** [comment]
on nes and the nimbus controller is hard playing super mario when A is run and B is jump
[img]http://i.imgur.com/HKfQncl.png[/img]

it should be X to run and A to jump

**Comment by jonathantneal** [comment]
You found your way here because you bought a Steelseries Nimbus and were surprised by the NES button mappings in Provenence.

![Steelseries Nimbus](https://cloud.githubusercontent.com/assets/188426/11453943/919ee400-95eb-11e5-85a1-c16284ad970b.png)

You expected the Nimbus X button to map to the NES B button, and the Nimbus Y button to map to the NES A button.

![image](https://cloud.githubusercontent.com/assets/188426/11453948/bd95c16e-95eb-11e5-89e1-68ff882f2b11.png)

Instead, the Nimbus A button maps to the NES B button. and the Nimbus B button maps to the NES A button.

> That's by design. Start and select had to go some where. On a standard controller without triggers, the only buttons not in use on NES were the X and Y buttons. So I assigned them to start and select... you can wait until the customizable controller mapping is implemented

Here are two solutions:

1. Wait until a button mapping feature is made available. Be really thankful for this software in its current form, and applaud @jasarien for his efforts.

2. Figure out how to change the mappings yourself and share the solution here. I’ve tried playing with `PVNESControllerViewController.m`, myself, which has not worked. Good luck, fellow novices. :)

**Comment by appletv4** [comment]
Or 3. download this which I have been using 
https://github.com/nlflint/Provenance.git

**Comment by OutRunner** [comment]
I don't know if should submit this as a separate enhancement request, but would it be possible to add turbo-fire to the possible button mappings?

So for example in Contra, instead of mapping NES B to Gamepad A, I could map NES Turbo B to Gamepad A. 

This does possibly open up the need for per-game mappings though as you probably wouldn't want to keep remapping the controls every time you switch between say Mario and Contra.

**Comment by MysticalOS** [comment]
One of features I like most about GBA4iOS is ability to change button layout. It's particularly a thing with gameboy advance titles since often times they were ports of SNES games so they often use L and R for main buttons that were intended to be held or used at same time as B and A things. Super mario advance 2 (super mario world) is one such example. in these cases trying to press two buttons that aren't next to each other, when the game plays like they SHOULD be next to each other can be tedious. In these cases I often swap L and R with X and Y buttons in GBA4iOS setup. this basically moves start/select (which are often bound to X and Y) to L and R which makes more sense. It makes a lot of GBA games easier to play.

if not full customizing then perhaps at least ability for GBA to swap L and R with X and Y (select/start). Then i can switch to a single emulator solution and not need to keep GBA4iOS for GBA (only thing i use it for, i use Prov for all other systems).

This kind of feature probably only make sense per system though, not globally. Heck I can't even really imagine it'd be useful outside GBA mapping actually. most of other system have good mapping.

**Comment by Dochartaigh** [comment]
How do we get to "PVNES/NES/PVNESEmulatorCore.mm" to find the "extendedGamepad" section to  edit the controller key mappings? (I'm trying to change the A, B, X, Y buttons on my Bluetooth controller to how they are on every other emulator I've ever used). 

The only way I have to access files on my iPhone (since Provenance is sideloaded) is though the "Import/Export ROMs and Saves" feature of the App, and there's no "PVNES" folder I see there. I'm assuming with XCode? (which I'm downloading right now and have only used for like 10 minutes before...) Thanks!

**Comment by QuarterSwede** [comment]
Is anyone working on adding customizable button remapping?

**Comment by jasonmlnsn** [comment]
I have tvOS 10.1
Provenance:
Version:  1.3.1(645)
Mode Release
Git v. d5f1b74
SteelSeries Nimbus remote with latest firmware

When using any emulator, example NES, or SEGA, I press B on the controller and it performs either a jump and action, but also opens up the menu.  It does both.  What could cause this?

**Comment by MoeMagoo** [comment]
i'm also having the same image as jasonminsn. Version 1.2.7 works properly, but not the newer versions

**Comment by jasarien** [comment]
@MoeMagoo this has been fixed in the latest code.

**Comment by MoeMagoo** [comment]
just tried on 

1.3.2.(655) 
5b7e242 
Release version with SteelSeries controller pulled down this afternoon. Tried with all 4 iCade options, including disabled, problem still occurs in SNES titles

**Comment by jasarien** [comment]
Which steelseries controller? As far as I'm aware steel series controllers are MFI controllers. Why are you using iCade options with them?

**Comment by MoeMagoo** [comment]
A Nimbus steel series. I just ran down the options list after trying it with iCade disabled. Not really life ending, I've rolled back to 1.2.7 for now. 

Appreciate the hard work!

**Comment by jasarien** [comment]
So yeah, the nimbus is an MFi controller, the iCade options won't have any effect since it's not an iCade controller. I don't know for certain, but it might trigger some code paths that may cause bugs like the b button triggering the menu etc.

**Comment by geoffbdp** [comment]
Hi ! First of All thanks for the excellent work! I have SteelSeries Stratus XL and use Provenance 1.3.2 and have the exact same problem when playing Genesis or SNES games: when pressing B it performs jump and action and opens up the menu.

**Comment by QuarterSwede** [comment]
I just updated to 1.3.2 and have a Steelseries Nimbus and just played a bunch of levels in Super Mario World on tvOS 10.1 without an issue. All buttons work as they should. Not sure what's going on with the others. This is the only controller I have paired with my Apple TV.

**Comment by appletv4** [comment]
@jasarien I was curious so I got my horipad ultimate out to test ,(been using 8bitdo controllers since icade was added )
This MFI controller 
https://9to5mac.files.wordpress.com/2015/12/horipadultimate-9.jpg?w=1600&h=1000

And I had the same problem as magoo, I hit "B" during a game , nes,snes sega and the menu pops up 

What fixed it for me was removing provenance from the background and reopening the app 

@MoeMagoo  did you try that ?

**Comment by samgreen** [comment]
I would like to add this and plan to post my design discussion for the PR in this thread.

**Comment by appletv4** [comment]
@samgreen can you also add button mapping for icade

**Comment by samgreen** [comment]
My first instinct is to emulate (ha!, get it?) what OpenEmu has done for mapping. Details here:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Controls

I like that regardless of what controller you are using, the mapping will work flawlessly. In regards to @appletv4 comment, this should allow us to map *any* controller to the inputs required for each system. This will make the code a bit more complex but will allow Provenance to function closer to something like RetroArch wherein you map the buttons once, and they work both in the front end to select games, and in the back end when you are actually controlling the games.

I would **love** to see the controller configuration resemble RetroArch. Details are here:

https://github.com/retropie/retropie-setup/wiki/retroarch-configuration#autoconfigurations

I would really love to follow suit and add similar hot keys for saving, loading, changing save slots, and returning to the front end menu.

Thoughts?

**Comment by xxTRONKOxx** [comment]
It would be nice if there was a button layout option so that I could change the button layout on my 8bitdo zero icade controller because it doesn't come in the button layout that it's supposed to be. All and all, I love this app

**Comment by Sega-Zero** [comment]
Can you please guide me to a place where I could make a turbo buttons implementation for 8bitdo controllers? Really miss that in NES games.

**Comment by AlexanderVarela** [comment]
Hello I would like to know how to can I remap the controller (ipega 9025) myself for PlayStation buttons and how can I access the file. I have an iPhone X non-jailbreak. Can you guys please guide me in the right direction. Thank you guys....

**Comment by jerok** [comment]
I hope this problem would be fixed in the future. Have the Madcats Mfi Pad and i wish i could set the buttons to my own choice.

**Comment by star104** [comment]
I just bought a steelseries controller and for some reason the A B and buttons are backwards on the NES/SNES emulators.

**Comment by sevdestruct** [comment]
@radiostorm - They are mapped based on their original physical positions as much as possible. Ignore the button labels on your controller which is based on Xbox I think—anyhow, they are irrelevant to the various emulated systems in Provenance.

Full list of control mapping for MFi controllers (such as Steelserires Nimbus) for all systems can be found here: [Controls][https://bit.ly/2LDZNzI]. 

In the future please don't use the Issues threads to pose questions like this unless it is to further along the Issue topic specifically. Thank you.

**Comment by Strike-9344** [comment]
I am having trouble with the buttons assigned to my keyboard. I'm playing on iPhone and I connected a Bluetooth Keyboard to play PlayStation 1 games, but the button mapping is awful, the arrows are ok but what I could see pressing everything is that F is circle, enter is X, R is triangle, the mapping is all over the place. Did anyone came up with a way to configure manually the buttons in the emulator? I mean, Delta has a great way to remap controls. They have a list with all the controllers layouts where you touch the button and reassign with the button you press on your controller/keyboard and I think it is very easy to use. But Delta doesnt support playstation so I can't play the games I want there.
